# Generated by Django 5.1.5 on 2025-03-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_date']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-expiration_date']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='approval_status',
        ),
        migrations.AddField(
            model_name='alumni',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
    ]
