# Generated by Django 5.1.5 on 2025-03-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_alter_event_options_alter_job_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='approval_status',
        ),
        migrations.AddField(
            model_name='user',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
    ]
