# Generated by Django 5.1.5 on 2025-04-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_news_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='roll_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
