# Generated by Django 5.1.5 on 2025-04-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_alumni_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='roll_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
