# Generated by Django 5.1.5 on 2025-04-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_alter_alumni_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics/'),
        ),
    ]
