# Generated by Django 5.1.5 on 2025-04-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0008_alumni_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer not to say', 'Prefer not to say')], default='prefer_not_to_say', max_length=20),
        ),
    ]
