# Generated by Django 5.1.5 on 2025-04-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0009_alter_alumni_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
