# Generated by Django 5.1.5 on 2025-04-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0010_alumni_github_alumni_linkedin_alumni_twitter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
