# Generated by Django 5.1.5 on 2025-04-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0011_alumni_facebook_alumni_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='registration_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
